#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
	exit;
}

require __DIR__ . '/vendor/autoload.php';

use Pauldro\Minicli\App\App;

$app = new App([
	'theme' => '\Unicorn',
	'app_path' => __DIR__ . '/app/Cmd',
	'env_dir'  => __DIR__,
]);
$app->setSignature("./script ");
$app->runCommand($argv);
